name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
          cache: 'pip'

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: |
          uv pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: |
            ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Test installation from Test PyPI
        run: |
          # Wait a bit for package to be available
          sleep 30
          # Create new venv for testing
          python -m venv test_venv
          source test_venv/bin/activate
          # Install from Test PyPI
          pip install --index-url https://test.pypi.org/simple/ \
                      --extra-index-url https://pypi.org/simple \
                      kde_colors==${{ github.event.release.tag_name }}
          # Basic import test
          python -c "import kde_colors; print(kde_colors.__version__)"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: |
            ${{ secrets.PYPI_TOKEN }}
